"""create V1 ServiceHub schema

Revision ID: 3481a60260c3
Revises: d83f10d9a936
Create Date: 2026-09-29 11:40:06.784635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3481a60260c3'
down_revision: Union[str, Sequence[str], None] = 'd83f10d9a936'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('entity_type', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('entity_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_track_id'), table_name='audit_logs')
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'metadata')
    op.drop_column('audit_logs', 'request_id')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'track_id')
    op.add_column('provider_verifications', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_verifications', 'rejection_reason')
    op.add_column('audit_logs', sa.Column('track_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('resource_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_track_id'), 'audit_logs', ['track_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource'), 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.drop_column('audit_logs', 'metadata_')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'entity_type')
    # ### end Alembic commands ###
