"""create V1 database schema

Revision ID: a8b2bd719324
Revises: 6220fd5b2970
Create Date: 2026-09-19 13:51:24.462362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8b2bd719324'
down_revision: Union[str, Sequence[str], None] = '6220fd5b2970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.create_table('service_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_service_categories_is_active', 'service_categories', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('CUSTOMER', 'PROVIDER', 'ADMIN')", name='ck_users_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED')", name='ck_users_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'UNREAD'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('UNREAD', 'READ')", name='ck_notifications_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text("status = 'UNREAD'"))
    op.create_table('provider_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('timezone', sa.String(length=100), server_default=sa.text("'Asia/Kolkata'"), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED')", name='ck_provider_profiles_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_provider_profiles_status', 'provider_profiles', ['status'], unique=False)
    op.create_table('availability',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_availability_day_of_week'),
    sa.CheckConstraint('start_time < end_time', name='ck_availability_time_range'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_availability_provider_active', 'availability', ['provider_id', 'is_active'], unique=False)
    op.create_index('ix_availability_provider_day', 'availability', ['provider_id', 'day_of_week'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='ck_services_duration_positive'),
    sa.CheckConstraint('price >= 0', name='ck_services_price_non_negative'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'id', name='uq_services_provider_id_id')
    )
    op.create_index('ix_services_category_active', 'services', ['category_id', 'is_active'], unique=False)
    op.create_index('ix_services_category_id', 'services', ['category_id'], unique=False)
    op.create_index('ix_services_provider_active', 'services', ['provider_id', 'is_active'], unique=False)
    op.create_index('ix_services_provider_id', 'services', ['provider_id'], unique=False)
    op.create_table(
    'bookings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('service_id', sa.BigInteger(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column(
        'status',
        sa.String(length=20),
        server_default=sa.text("'PENDING'"),
        nullable=False,
    ),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('provider_notes', sa.Text(), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('CURRENT_TIMESTAMP'),
        nullable=False,
    ),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),

    sa.CheckConstraint(
        'start_at < end_at',
        name='ck_bookings_time_range',
    ),
    sa.CheckConstraint(
        "status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'IN_PROGRESS', 'COMPLETED')",
        name='ck_bookings_status',
    ),

    sa.ForeignKeyConstraint(
        ['customer_id'],
        ['users.id'],
        ondelete='RESTRICT',
    ),
    sa.ForeignKeyConstraint(
        ['provider_id', 'service_id'],
        ['services.provider_id', 'services.id'],
        name='fk_bookings_provider_service',
        ondelete='RESTRICT',
    ),
    sa.ForeignKeyConstraint(
        ['provider_id'],
        ['provider_profiles.id'],
        ondelete='RESTRICT',
    ),

    sa.PrimaryKeyConstraint('id'),
)

    op.execute("""
        ALTER TABLE bookings
        ADD CONSTRAINT no_provider_overlapping_bookings
        EXCLUDE USING gist (
            provider_id gist_int8_ops WITH =,
            tstzrange(start_at, end_at, '[)') WITH &&
        )
        WHERE (
            status IN ('PENDING', 'CONFIRMED', 'IN_PROGRESS')
        )
    """)
    op.create_index('ix_bookings_active_provider_start', 'bookings', ['provider_id', 'start_at'], unique=False, postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED', 'IN_PROGRESS')"))
    op.create_index('ix_bookings_customer_created', 'bookings', ['customer_id', 'created_at'], unique=False)
    op.create_index('ix_bookings_provider_start', 'bookings', ['provider_id', 'start_at'], unique=False)
    op.create_index('ix_bookings_provider_status', 'bookings', ['provider_id', 'status'], unique=False)
    op.create_index('ix_bookings_service_id', 'bookings', ['service_id'], unique=False)
    op.create_index('ix_bookings_start_at', 'bookings', ['start_at'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index('ix_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('ix_reviews_customer_id', 'reviews', ['customer_id'], unique=False)
    op.create_index('ix_reviews_provider_id', 'reviews', ['provider_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_provider_id', table_name='reviews')
    op.drop_index('ix_reviews_customer_id', table_name='reviews')
    op.drop_index('ix_reviews_created_at', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_bookings_start_at', table_name='bookings')
    op.drop_index('ix_bookings_service_id', table_name='bookings')
    op.drop_index('ix_bookings_provider_status', table_name='bookings')
    op.drop_index('ix_bookings_provider_start', table_name='bookings')
    op.drop_index('ix_bookings_customer_created', table_name='bookings')
    op.drop_index('ix_bookings_active_provider_start', table_name='bookings', postgresql_where=sa.text("status IN ('PENDING', 'CONFIRMED', 'IN_PROGRESS')"))
    op.drop_table('bookings')
    op.drop_index('ix_services_provider_id', table_name='services')
    op.drop_index('ix_services_provider_active', table_name='services')
    op.drop_index('ix_services_category_id', table_name='services')
    op.drop_index('ix_services_category_active', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_availability_provider_day', table_name='availability')
    op.drop_index('ix_availability_provider_active', table_name='availability')
    op.drop_table('availability')
    op.drop_index('ix_provider_profiles_status', table_name='provider_profiles')
    op.drop_table('provider_profiles')
    op.drop_index('ix_notifications_user_unread', table_name='notifications', postgresql_where=sa.text("status = 'UNREAD'"))
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_service_categories_is_active', table_name='service_categories')
    op.drop_table('service_categories')
    # ### end Alembic commands ###
