"""create v1 servicehub schema

Revision ID: d83f10d9a936
Revises: 
Create Date: 2026-09-26 14:09:48.248057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83f10d9a936'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), server_default='IN', nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_addresses_city', 'addresses', ['city'], unique=False)
    op.create_index('ix_addresses_postal_code', 'addresses', ['postal_code'], unique=False)
    op.create_index('ix_addresses_state', 'addresses', ['state'], unique=False)
    op.create_table('service_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_categories_name', 'service_categories', ['name'], unique=False)
    op.create_index('ix_service_categories_parent_id', 'service_categories', ['parent_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CUSTOMER', 'PROVIDER', name='user_role'), server_default='CUSTOMER', nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='user_status'), server_default='ACTIVE', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('track_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_user_id', 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_request_id', 'audit_logs', ['request_id'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_track_id', 'audit_logs', ['track_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.Enum('BOOKING_CREATED', 'BOOKING_CONFIRMED', 'BOOKING_ASSIGNED', 'BOOKING_RESCHEDULED', 'BOOKING_CANCELLED', 'PAYMENT_SUCCESS', 'PAYMENT_FAILED', 'SERVICE_STARTED', 'SERVICE_COMPLETED', 'REVIEW_REQUEST', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'ARCHIVED', name='notification_status'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('provider_organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='provider_status'), server_default='PENDING', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_organizations_created_by', 'provider_organizations', ['created_by'], unique=False)
    op.create_index('ix_provider_organizations_name', 'provider_organizations', ['name'], unique=False)
    op.create_index('ix_provider_organizations_status', 'provider_organizations', ['status'], unique=False)
    op.create_table('provider_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('business_contact_email', sa.String(length=255), nullable=True),
    sa.Column('business_contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_provider_profiles_user_id', 'provider_profiles', ['user_id'], unique=False)
    op.create_table('user_addresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'address_id', name='uq_user_addresses_user_address')
    )
    op.create_index('ix_user_addresses_address_id', 'user_addresses', ['address_id'], unique=False)
    op.create_index('ix_user_addresses_user_id', 'user_addresses', ['user_id'], unique=False)
    op.create_table('provider_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location_type', sa.Enum('SHOP', 'OFFICE', 'SERVICE_CENTER', name='provider_location_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['provider_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_locations_address_id', 'provider_locations', ['address_id'], unique=False)
    op.create_index('ix_provider_locations_location_type', 'provider_locations', ['location_type'], unique=False)
    op.create_index('ix_provider_locations_organization_id', 'provider_locations', ['organization_id'], unique=False)
    op.create_table('provider_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'AGENT', name='provider_membership_role'), nullable=False),
    sa.Column('agent_type', sa.Enum('MOBILE', 'ON_SITE', 'HYBRID', name='agent_type'), nullable=True),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'SUSPENDED', 'REMOVED', name='membership_status'), server_default='INVITED', nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("\n            (\n                role = 'AGENT'\n                AND agent_type IS NOT NULL\n            )\n            OR\n            (\n                role IN ('OWNER', 'MANAGER')\n                AND agent_type IS NULL\n            )\n            ", name='ck_provider_memberships_agent_type_by_role'),
    sa.CheckConstraint("\n            (\n                status = 'INVITED'\n                AND joined_at IS NULL\n            )\n            OR\n            status != 'INVITED'\n            ", name='ck_provider_memberships_invitation_state'),
    sa.ForeignKeyConstraint(['organization_id'], ['provider_organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_memberships_organization_id', 'provider_memberships', ['organization_id'], unique=False)
    op.create_index('ix_provider_memberships_role', 'provider_memberships', ['role'], unique=False)
    op.create_index('ix_provider_memberships_status', 'provider_memberships', ['status'], unique=False)
    op.create_index('ix_provider_memberships_user_id', 'provider_memberships', ['user_id'], unique=False)
    op.create_table('provider_service_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['provider_organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'postal_code', name='uq_provider_service_areas_org_postal_code')
    )
    op.create_index('ix_provider_service_areas_organization_id', 'provider_service_areas', ['organization_id'], unique=False)
    op.create_index('ix_provider_service_areas_postal_code', 'provider_service_areas', ['postal_code'], unique=False)
    op.create_table('provider_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='verification_status'), nullable=False),
    sa.Column('document_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['provider_organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_verifications_organization_id', 'provider_verifications', ['organization_id'], unique=False)
    op.create_index('ix_provider_verifications_reviewed_by', 'provider_verifications', ['reviewed_by'], unique=False)
    op.create_index('ix_provider_verifications_status', 'provider_verifications', ['status'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='service_status'), nullable=False),
    sa.Column('service_modes', sa.ARRAY(sa.Enum('HOME_SERVICE', 'AT_PROVIDER', name='service_mode')), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['provider_organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_services_category_id', 'services', ['category_id'], unique=False)
    op.create_index('ix_services_organization_id', 'services', ['organization_id'], unique=False)
    op.create_index('ix_services_status', 'services', ['status'], unique=False)
    op.create_table('agent_availability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_membership_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_membership_id'], ['provider_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_membership_id', 'day_of_week', 'start_time', 'end_time', name='uq_agent_availability_period')
    )
    op.create_index('ix_agent_availability_agent_membership_id', 'agent_availability', ['agent_membership_id'], unique=False)
    op.create_table('agent_time_off',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_membership_id', sa.UUID(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_membership_id'], ['provider_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_time_off_agent_membership_id', 'agent_time_off', ['agent_membership_id'], unique=False)
    op.create_index('ix_agent_time_off_ends_at', 'agent_time_off', ['ends_at'], unique=False)
    op.create_index('ix_agent_time_off_starts_at', 'agent_time_off', ['starts_at'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('service_mode', sa.Enum('HOME_SERVICE', 'AT_PROVIDER', name='service_mode'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'ASSIGNMENT_PENDING', 'ASSIGNED', 'RESCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'DISPUTED', name='booking_status'), nullable=False),
    sa.Column('customer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['provider_organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_customer_id', 'bookings', ['customer_id'], unique=False)
    op.create_index('ix_bookings_org_schedule', 'bookings', ['organization_id', 'scheduled_start'], unique=False)
    op.create_index('ix_bookings_organization_id', 'bookings', ['organization_id'], unique=False)
    op.create_index('ix_bookings_scheduled_start', 'bookings', ['scheduled_start'], unique=False)
    op.create_index('ix_bookings_service_id', 'bookings', ['service_id'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_table('provider_operating_hours',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_location_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=True),
    sa.Column('closes_at', sa.Time(), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_location_id'], ['provider_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_location_id', 'day_of_week', name='uq_provider_operating_hours_location_day')
    )
    op.create_index('ix_provider_operating_hours_location_id', 'provider_operating_hours', ['provider_location_id'], unique=False)
    op.create_table('service_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirement_type', sa.Enum('TEXT', 'NUMBER', 'BOOLEAN', 'SINGLE_SELECT', 'MULTI_SELECT', 'FILE', name='requirement_type'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_requirements_service_id', 'service_requirements', ['service_id'], unique=False)
    op.create_table('booking_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('agent_membership_id', sa.UUID(), nullable=False),
    sa.Column('reassigned_from_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ASSIGNED', 'ACCEPTED', 'DECLINED', 'EN_ROUTE', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'REASSIGNED', name='assignment_status'), nullable=False),
    sa.Column('assignment_note', sa.String(length=500), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_membership_id'], ['provider_memberships.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reassigned_from_id'], ['booking_assignments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_assignments_agent_membership_id', 'booking_assignments', ['agent_membership_id'], unique=False)
    op.create_index('ix_booking_assignments_booking_id', 'booking_assignments', ['booking_id'], unique=False)
    op.create_index('ix_booking_assignments_status', 'booking_assignments', ['status'], unique=False)
    op.create_table('booking_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index('ix_booking_locations_booking_id', 'booking_locations', ['booking_id'], unique=False)
    op.create_index('ix_booking_locations_postal_code', 'booking_locations', ['postal_code'], unique=False)
    op.create_table('booking_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'ASSIGNMENT_PENDING', 'ASSIGNED', 'RESCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'DISPUTED', name='booking_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_status_history_booking_id', 'booking_status_history', ['booking_id'], unique=False)
    op.create_index('ix_booking_status_history_created_at', 'booking_status_history', ['created_at'], unique=False)
    op.create_table('booking_travel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'EN_ROUTE', 'ARRIVED', 'CANCELLED', 'COMPLETED', name='travel_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index('ix_booking_travel_booking_id', 'booking_travel', ['booking_id'], unique=False)
    op.create_index('ix_booking_travel_status', 'booking_travel', ['status'], unique=False)
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', 'CLOSED', name='dispute_status'), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_disputes_booking_id', 'disputes', ['booking_id'], unique=False)
    op.create_index('ix_disputes_raised_by', 'disputes', ['raised_by'], unique=False)
    op.create_index('ix_disputes_status', 'disputes', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PAID', 'VOID', 'REFUNDED', name='invoice_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index('ix_invoices_booking_id', 'invoices', ['booking_id'], unique=False)
    op.create_index('ix_invoices_status', 'invoices', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.Enum('DUMMY', 'CARD', 'UPI', 'NET_BANKING', 'WALLET', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHORIZED', 'PAID', 'FAILED', 'CANCELLED', 'REFUND_PENDING', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index('ix_payments_booking_id', 'payments', ['booking_id'], unique=False)
    op.create_index('ix_payments_provider_reference', 'payments', ['provider_reference'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_table('provider_settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', 'CANCELLED', name='settlement_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['provider_organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_settlements_booking_id', 'provider_settlements', ['booking_id'], unique=False)
    op.create_index('ix_provider_settlements_organization_id', 'provider_settlements', ['organization_id'], unique=False)
    op.create_index('ix_provider_settlements_status', 'provider_settlements', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PUBLISHED', 'HIDDEN', 'REMOVED', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['provider_organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_reviews_booking_id')
    )
    op.create_index('ix_reviews_customer_id', 'reviews', ['customer_id'], unique=False)
    op.create_index('ix_reviews_organization_id', 'reviews', ['organization_id'], unique=False)
    op.create_index('ix_reviews_status', 'reviews', ['status'], unique=False)
    op.create_table('service_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'RESOLVED', 'CLOSED', name='service_issue_status'), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_service_issues_booking_id', 'service_issues', ['booking_id'], unique=False)
    op.create_index('ix_service_issues_customer_id', 'service_issues', ['customer_id'], unique=False)
    op.create_index('ix_service_issues_status', 'service_issues', ['status'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='refund_status'), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refunds_payment_id', 'refunds', ['payment_id'], unique=False)
    op.create_index('ix_refunds_status', 'refunds', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('PAYMENT', 'REFUND', 'COMMISSION', 'PROVIDER_SETTLEMENT', 'ADJUSTMENT', 'FEE', name='transaction_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['provider_organizations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_created_at', 'transactions', ['created_at'], unique=False)
    op.create_index('ix_transactions_organization_id', 'transactions', ['organization_id'], unique=False)
    op.create_index('ix_transactions_payment_id', 'transactions', ['payment_id'], unique=False)
    op.create_index('ix_transactions_transaction_type', 'transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_transaction_type', table_name='transactions')
    op.drop_index('ix_transactions_payment_id', table_name='transactions')
    op.drop_index('ix_transactions_organization_id', table_name='transactions')
    op.drop_index('ix_transactions_created_at', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_refunds_status', table_name='refunds')
    op.drop_index('ix_refunds_payment_id', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_service_issues_status', table_name='service_issues')
    op.drop_index('ix_service_issues_customer_id', table_name='service_issues')
    op.drop_index('ix_service_issues_booking_id', table_name='service_issues')
    op.drop_table('service_issues')
    op.drop_index('ix_reviews_status', table_name='reviews')
    op.drop_index('ix_reviews_organization_id', table_name='reviews')
    op.drop_index('ix_reviews_customer_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_provider_settlements_status', table_name='provider_settlements')
    op.drop_index('ix_provider_settlements_organization_id', table_name='provider_settlements')
    op.drop_index('ix_provider_settlements_booking_id', table_name='provider_settlements')
    op.drop_table('provider_settlements')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_provider_reference', table_name='payments')
    op.drop_index('ix_payments_booking_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_invoices_status', table_name='invoices')
    op.drop_index('ix_invoices_booking_id', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_disputes_status', table_name='disputes')
    op.drop_index('ix_disputes_raised_by', table_name='disputes')
    op.drop_index('ix_disputes_booking_id', table_name='disputes')
    op.drop_table('disputes')
    op.drop_index('ix_booking_travel_status', table_name='booking_travel')
    op.drop_index('ix_booking_travel_booking_id', table_name='booking_travel')
    op.drop_table('booking_travel')
    op.drop_index('ix_booking_status_history_created_at', table_name='booking_status_history')
    op.drop_index('ix_booking_status_history_booking_id', table_name='booking_status_history')
    op.drop_table('booking_status_history')
    op.drop_index('ix_booking_locations_postal_code', table_name='booking_locations')
    op.drop_index('ix_booking_locations_booking_id', table_name='booking_locations')
    op.drop_table('booking_locations')
    op.drop_index('ix_booking_assignments_status', table_name='booking_assignments')
    op.drop_index('ix_booking_assignments_booking_id', table_name='booking_assignments')
    op.drop_index('ix_booking_assignments_agent_membership_id', table_name='booking_assignments')
    op.drop_table('booking_assignments')
    op.drop_index('ix_service_requirements_service_id', table_name='service_requirements')
    op.drop_table('service_requirements')
    op.drop_index('ix_provider_operating_hours_location_id', table_name='provider_operating_hours')
    op.drop_table('provider_operating_hours')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_service_id', table_name='bookings')
    op.drop_index('ix_bookings_scheduled_start', table_name='bookings')
    op.drop_index('ix_bookings_organization_id', table_name='bookings')
    op.drop_index('ix_bookings_org_schedule', table_name='bookings')
    op.drop_index('ix_bookings_customer_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_agent_time_off_starts_at', table_name='agent_time_off')
    op.drop_index('ix_agent_time_off_ends_at', table_name='agent_time_off')
    op.drop_index('ix_agent_time_off_agent_membership_id', table_name='agent_time_off')
    op.drop_table('agent_time_off')
    op.drop_index('ix_agent_availability_agent_membership_id', table_name='agent_availability')
    op.drop_table('agent_availability')
    op.drop_index('ix_services_status', table_name='services')
    op.drop_index('ix_services_organization_id', table_name='services')
    op.drop_index('ix_services_category_id', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_provider_verifications_status', table_name='provider_verifications')
    op.drop_index('ix_provider_verifications_reviewed_by', table_name='provider_verifications')
    op.drop_index('ix_provider_verifications_organization_id', table_name='provider_verifications')
    op.drop_table('provider_verifications')
    op.drop_index('ix_provider_service_areas_postal_code', table_name='provider_service_areas')
    op.drop_index('ix_provider_service_areas_organization_id', table_name='provider_service_areas')
    op.drop_table('provider_service_areas')
    op.drop_index('ix_provider_memberships_user_id', table_name='provider_memberships')
    op.drop_index('ix_provider_memberships_status', table_name='provider_memberships')
    op.drop_index('ix_provider_memberships_role', table_name='provider_memberships')
    op.drop_index('ix_provider_memberships_organization_id', table_name='provider_memberships')
    op.drop_table('provider_memberships')
    op.drop_index('ix_provider_locations_organization_id', table_name='provider_locations')
    op.drop_index('ix_provider_locations_location_type', table_name='provider_locations')
    op.drop_index('ix_provider_locations_address_id', table_name='provider_locations')
    op.drop_table('provider_locations')
    op.drop_index('ix_user_addresses_user_id', table_name='user_addresses')
    op.drop_index('ix_user_addresses_address_id', table_name='user_addresses')
    op.drop_table('user_addresses')
    op.drop_index('ix_provider_profiles_user_id', table_name='provider_profiles')
    op.drop_table('provider_profiles')
    op.drop_index('ix_provider_organizations_status', table_name='provider_organizations')
    op.drop_index('ix_provider_organizations_name', table_name='provider_organizations')
    op.drop_index('ix_provider_organizations_created_by', table_name='provider_organizations')
    op.drop_table('provider_organizations')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_status', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_audit_logs_track_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_request_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_phone', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_service_categories_parent_id', table_name='service_categories')
    op.drop_index('ix_service_categories_name', table_name='service_categories')
    op.drop_table('service_categories')
    op.drop_index('ix_addresses_state', table_name='addresses')
    op.drop_index('ix_addresses_postal_code', table_name='addresses')
    op.drop_index('ix_addresses_city', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
