"""add provider service offerings

Revision ID: e266e939902f
Revises: 067306050483
Create Date: 2026-10-03 04:31:55.955456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e266e939902f'
down_revision: Union[str, Sequence[str], None] = '067306050483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_service_offerings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('service_modes', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('array_length(service_modes, 1) >= 1', name='ck_provider_service_offerings_service_modes_not_empty'),
    sa.CheckConstraint('buffer_minutes >= 0', name='ck_provider_service_offerings_buffer_non_negative'),
    sa.CheckConstraint('duration_minutes > 0', name='ck_provider_service_offerings_duration_positive'),
    sa.CheckConstraint('price >= 0', name='ck_provider_service_offerings_price_non_negative'),
    sa.ForeignKeyConstraint(['organization_id'], ['provider_organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'service_id', name='uq_provider_service_offerings_organization_service')
    )
    op.create_index('ix_provider_service_offerings_is_active', 'provider_service_offerings', ['is_active'], unique=False)
    op.create_index('ix_provider_service_offerings_organization_id', 'provider_service_offerings', ['organization_id'], unique=False)
    op.create_index('ix_provider_service_offerings_service_id', 'provider_service_offerings', ['service_id'], unique=False)
    op.create_table('provider_service_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_service_offering_id', sa.UUID(), nullable=False),
    sa.Column('provider_membership_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['provider_membership_id'], ['provider_memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_service_offering_id'], ['provider_service_offerings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_service_offering_id', 'provider_membership_id', name='uq_provider_service_member_offering_membership')
    )
    op.create_index('ix_provider_service_members_is_active', 'provider_service_members', ['is_active'], unique=False)
    op.create_index('ix_provider_service_members_membership_id', 'provider_service_members', ['provider_membership_id'], unique=False)
    op.create_index('ix_provider_service_members_offering_id', 'provider_service_members', ['provider_service_offering_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_provider_service_members_offering_id', table_name='provider_service_members')
    op.drop_index('ix_provider_service_members_membership_id', table_name='provider_service_members')
    op.drop_index('ix_provider_service_members_is_active', table_name='provider_service_members')
    op.drop_table('provider_service_members')
    op.drop_index('ix_provider_service_offerings_service_id', table_name='provider_service_offerings')
    op.drop_index('ix_provider_service_offerings_organization_id', table_name='provider_service_offerings')
    op.drop_index('ix_provider_service_offerings_is_active', table_name='provider_service_offerings')
    op.drop_table('provider_service_offerings')
    # ### end Alembic commands ###
